language: python
python:
    - "3.5"
addons:
  apt:
    packages:
      - graphviz
before_install:
    - openssl aes-256-cbc -K $encrypted_8e28d6063879_key -iv $encrypted_8e28d6063879_iv -in interact_key.enc -out ~/.ssh/publish-key -d
install:
    - pip install jupyter
    - pip install nbval
    - pip install matplotlib
    - pip install graphviz
    - pip install sympy
    - pip install sklearn
    - pip install scipy
    - pip install seaborn
    - pip install ghp-import
script:
    - py.test --nbval-lax *.ipynb
    - git clone https://github.com/christianp/jupyter-interactions-site
    - cp jupyter-interactions-site/config.yml.dist jupyter-interactions-site/config.yml
    - sed -i s#http://localhost:8888/notebooks/jupyter-interactions/#https://github.com/mikecroucher/jupyter-interactions/blob/master/# jupyter-interactions-site/config.yml
    - sed -i s#../jupyter-interactions#../# jupyter-interactions-site/config.yml
    - pip install -r jupyter-interactions-site/requirements.txt
    - cd jupyter-interactions-site
    - python build_site.py
    - chmod u=rw,og= ~/.ssh/publish-key
    - echo "Host github.com" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
    - git clone https://github.com/mikecroucher/jupyter-interactions -b gh-pages
    - cd jupyter-interactions
    - ghp-import -n -p -m "Update gh-pages." ./../site
