language: python
python:
    - "3.5"
addons:
  apt:
    packages:
      - graphviz
before_install:
    - pip install IPython
    - pip install nbformat
    - python helpers/gen_req_txt_from_notebooks.py --nbs_dir=. --req_txt_fname=helpers/requirements.txt
install:
    - pip install nbval
    - pip install ghp-import
    - pip install -r helpers/requirements.txt
script:
    # Testing
    - ./test_all_notebooks.sh
    # Build Website
    - ./build_website.sh
