language: python
python:
    - "3.5"
addons:
  apt:
    packages:
      - graphviz
before_install:
    - pip install IPython
    - pip install nbformat
    - python helpers/gen_req_txt_from_notebooks.py --nbs_dir=. --req_txt_fname=helpers/requirements.txt
install:
    - pip install nbval
    - pip install ghp-import
    - pip install -r helpers/requirements.txt
script:
   # If this is a PR, just test the notebooks
   - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./test_all_notebooks.sh; fi
   # If it's not a PR, test all notebooks and then build the website
   - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./test_all_notebooks.sh;bash ./build_website.sh; fi
